function ReportTable() {

  const reports = [
    {
      id: "RP001",
      name: "Monthly Asset Report",
      generatedBy: "Admin",
      date: "12 Jul 2026",
      type: "PDF",
    },
    {
      id: "RP002",
      name: "Maintenance Summary",
      generatedBy: "Manager",
      date: "10 Jul 2026",
      type: "CSV",
    },
    {
      id: "RP003",
      name: "Booking Analysis",
      generatedBy: "Admin",
      date: "08 Jul 2026",
      type: "PDF",
    },
  ];

  return (
    <div className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-md">

      <table className="w-full">

        <thead className="bg-slate-900 text-white">

          <tr>

            <th className="px-6 py-4 text-left">Report ID</th>

            <th className="px-6 py-4 text-left">Report Name</th>

            <th className="px-6 py-4 text-left">Generated By</th>

            <th className="px-6 py-4 text-left">Generated On</th>

            <th className="px-6 py-4 text-left">Type</th>

            <th className="px-6 py-4 text-center">Action</th>

          </tr>

        </thead>

        <tbody>

          {reports.map((report) => (

            <tr key={report.id} className="border-t hover:bg-slate-50">

              <td className="px-6 py-4 font-medium">{report.id}</td>

              <td className="px-6 py-4">{report.name}</td>

              <td className="px-6 py-4">{report.generatedBy}</td>

              <td className="px-6 py-4">{report.date}</td>

              <td className="px-6 py-4">{report.type}</td>

              <td className="px-6 py-4 text-center">

                <button className="rounded-lg bg-blue-100 px-4 py-2 text-sm text-blue-700 hover:bg-blue-600 hover:text-white">
                  Download
                </button>

              </td>

            </tr>

          ))}

        </tbody>

      </table>

    </div>
  );
}

export default ReportTable;